_BASE_: Base-RCNN-FPN.yaml
MODEL:
  BACKBONE:
    FREEZE_AT: 0
  ROI_HEADS:
    NAME: "Keypoints3DROIHeads"
    NUM_CLASSES: 2
  ROI_BOX_HEAD:
    SMOOTH_L1_BETA: 0.5
  RPN:
    POST_NMS_TOPK_TRAIN: 1500

