_BASE_: Base-Keypoints3D-RCNN-FPN.yaml
SEED: 12312
MODEL:
  WEIGHTS: ""
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 1
  ROI_KEYPOINTS3D_HEAD:
    NAME: "StandardKeypoints3DHead"

DATALOADER: 
  NUM_WORKERS: 0

TEST:
  EVAL_3D: True

DATASETS:
  TEST_SET_NAME: camma_mvor
  H36_STATS_PATH: ""
  DOWN_SAMPLING: True
  FIX_DOWN_SAMPLING: True
  DOWN_SAMPLING_FIX_SCALE: 10.0
  DOWN_SAMPLING_METHOD: "bilinear"